// @ts-check
import rootConfig from '../../eslint.config.mjs'
import nextPlugin from '@next/eslint-plugin-next'

export default [
  ...rootConfig,
  // next-env.d.ts is auto-generated by Next.js — must not be linted
  { ignores: ['next-env.d.ts'] },
  {
    plugins: {
      '@next/next': nextPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },
]
